### ISSUE TITLE
[Bug] The new update makes melee attacks from enemys instakill

### ISSUE THREAD

**Issue by Alf596** [kking117/RoR2-kking117Mods#21] opened 2022-12-18 04:38 UTC
After the update today, 1.14.2, any melee attack from a enemy will continuously keep hitting, leading to our immediate death.
This issues sprung today after the patch and we have no clue why.

**Comment by Moirim** [comment] 2022-12-18 17:43
To add on to Alf596, it has also broken several survivor skills, at least from what I've seen.

Commando:
- Phase Blast duplicates on hit with targets that aren't one shot
- Shotgun no longer hits more than one pellet

Huntress:
- Glaive no longer bounces between targets
- Ballista recoil doesn't work as intended, seems to be almost random

Captain:
- Tazer explodes several times on impact, and seems to try and bounce like Huntress' glaive
- Shotgun no longer hits for more than one pellet

Just to name a few. These were the only ones I experimented with, but may not be the only broken ones.

**Comment by kking117** [comment] 2022-12-18 20:46
I cannot replicate this with a clean install with just this mod so it's likely an incompatibility with another mod. I will need a log from a session this occurred in to troubleshoot this issue.

If you manually install mods without a manager it will be in your "BepInEx" folder and should be a file called "LogOutput.log".

If you are using r2modman, go to "Settings" -> "Locations" -> "Browse profile folder" and it will open up the file browser. Go into the "BepInEx" folder and it should be a file called "LogOutput.log".

**Comment by kking117** [comment] 2022-12-18 21:00
Actually never mind, I think I found the problem.

**Comment by kking117** [comment] 2022-12-19 00:00
The mod has been updated to 1.14.3 and includes a potential fix to the problem. Please close this issue if it's fixed.

**Closed** 2022-12-19 05:47 UTC
